language: go

sudo: false

git:
  depth: 1
  submodules: false

go:
  - "1.9"
  - "1.10"
  - "1.11"

env:
  - GOARCH=amd64

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - make vendor-install

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - make test-ci

after_success:
- bash <(curl -s https://codecov.io/bash)
